//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtosService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NtosService.NtosServiceSoap")]
    public interface NtosServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/what_is_my_ip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> what_is_my_ipAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/create_ser_user", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> create_ser_userAsync(string user_name, string user_password, string ip, string notes, string su, string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update_ser_user", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> update_ser_userAsync(string user_name, string user_password, string ip, string notes, string su, string sp);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_ser_users", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.get_ser_usersResponse> get_ser_usersAsync(NtosService.get_ser_usersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_ser_users_notes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.get_ser_users_notesResponseGet_ser_users_notesResult> get_ser_users_notesAsync(string tin);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chek", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.chekResponse> chekAsync(NtosService.chekRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/save_invoice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.save_invoiceResponse> save_invoiceAsync(NtosService.save_invoiceRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/save_invoice_a", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.save_invoice_aResponse> save_invoice_aAsync(NtosService.save_invoice_aRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_invoice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.get_invoiceResponse> get_invoiceAsync(NtosService.get_invoiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_invoice_desc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.get_invoice_descResponseGet_invoice_descResult> get_invoice_descAsync(int user_id, int invois_id, string su, string sp);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/save_invoice_desc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.save_invoice_descResponse> save_invoice_descAsync(NtosService.save_invoice_descRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete_invoice_desc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> delete_invoice_descAsync(int user_id, int id, int inv_id, string su, string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_ntos_invoices_inv_nos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.get_ntos_invoices_inv_nosResponseGet_ntos_invoices_inv_nosResult> get_ntos_invoices_inv_nosAsync(int user_id, int invois_id, string su, string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/save_ntos_invoices_inv_nos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> save_ntos_invoices_inv_nosAsync(int invois_id, int user_id, string overhead_no, System.DateTime overhead_dt, string su, string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete_ntos_invoices_inv_nos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> delete_ntos_invoices_inv_nosAsync(int user_id, int id, int inv_id, string su, string sp);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_un_id_from_tin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.get_un_id_from_tinResponse> get_un_id_from_tinAsync(NtosService.get_un_id_from_tinRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_tin_from_un_id", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.get_tin_from_un_idResponse> get_tin_from_un_idAsync(NtosService.get_tin_from_un_idRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_org_name_from_un_id", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> get_org_name_from_un_idAsync(int user_id, int un_id, string su, string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_un_id_from_user_id", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> get_un_id_from_user_idAsync(int user_id, string su, string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/change_invoice_status", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> change_invoice_statusAsync(int user_id, int inv_id, int status, string su, string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/acsept_invoice_status", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> acsept_invoice_statusAsync(int user_id, int inv_id, int status, string su, string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ref_invoice_status", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> ref_invoice_statusAsync(int user_id, int inv_id, string ref_text, string su, string sp);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/k_invoice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.k_invoiceResponse> k_invoiceAsync(NtosService.k_invoiceRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/g_invoice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.g_invoiceResponse> g_invoiceAsync(NtosService.g_invoiceRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_makoreqtirebeli", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.get_makoreqtirebeliResponse> get_makoreqtirebeliAsync(NtosService.get_makoreqtirebeliRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_seller_invoices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.get_seller_invoicesResponseGet_seller_invoicesResult> get_seller_invoicesAsync(int user_id, int un_id, System.DateTime s_dt, System.DateTime e_dt, System.DateTime op_s_dt, System.DateTime op_e_dt, string invoice_no, string sa_ident_no, string desc, string doc_mos_nom, string su, string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_buyer_invoices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.get_buyer_invoicesResponseGet_buyer_invoicesResult> get_buyer_invoicesAsync(int user_id, int un_id, System.DateTime s_dt, System.DateTime e_dt, System.DateTime op_s_dt, System.DateTime op_e_dt, string invoice_no, string sa_ident_no, string desc, string doc_mos_nom, string su, string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_invoice_numbers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.get_invoice_numbersResponseGet_invoice_numbersResult> get_invoice_numbersAsync(int user_id, int un_id, string v_invoice_n, int v_count, string su, string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_invoice_tins", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.get_invoice_tinsResponseGet_invoice_tinsResult> get_invoice_tinsAsync(int user_id, int un_id, string v_invoice_t, int v_count, string su, string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_invoice_d", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.get_invoice_dResponseGet_invoice_dResult> get_invoice_dAsync(int user_id, int un_id, string v_invoice_d, int v_count, string su, string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_seller_invoices_r", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.get_seller_invoices_rResponseGet_seller_invoices_rResult> get_seller_invoices_rAsync(int user_id, int un_id, int status, string su, string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_buyer_invoices_r", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.get_buyer_invoices_rResponseGet_buyer_invoices_rResult> get_buyer_invoices_rAsync(int user_id, int un_id, int status, string su, string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/print_invoices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.print_invoicesResponsePrint_invoicesResult> print_invoicesAsync(int user_id, int inv_id, string su, string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_akciz", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.get_akcizResponseGet_akcizResult> get_akcizAsync(string s_text, int user_id, string su, string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_seq_nums", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.get_seq_numsResponseGet_seq_numsResult> get_seq_numsAsync(string sag_periodi, int user_id, string su, string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/add_inv_to_decl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> add_inv_to_declAsync(int user_id, int seq_num, int inv_id, string su, string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/save_invoice_request", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> save_invoice_requestAsync(int inv_id, int user_id, int bayer_un_id, int seller_un_id, string overhead_no, System.DateTime dt, string notes, string su, string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/del_invoice_request", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> del_invoice_requestAsync(int inv_id, int user_id, int bayer_un_id, string su, string sp);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_invoice_request", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.get_invoice_requestResponse> get_invoice_requestAsync(NtosService.get_invoice_requestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/acsept_invoice_request_status", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> acsept_invoice_request_statusAsync(int id, int user_id, int seller_un_id, string su, string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_requested_invoices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.get_requested_invoicesResponseGet_requested_invoicesResult> get_requested_invoicesAsync(int user_id, int seller_un_id, string su, string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_invoice_requests", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.get_invoice_requestsResponseGet_invoice_requestsResult> get_invoice_requestsAsync(int bayer_un_id, int user_id, string su, string sp);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_seller_filter_count", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.get_seller_filter_countResponse> get_seller_filter_countAsync(NtosService.get_seller_filter_countRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_buyer_filter_count", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.get_buyer_filter_countResponse> get_buyer_filter_countAsync(NtosService.get_buyer_filter_countRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_invoice_changes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NtosService.get_invoice_changesResponseGet_invoice_changesResult> get_invoice_changesAsync(int user_id, System.DateTime st_date, System.DateTime end_date, string su, string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_invoice_id", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> get_invoice_idAsync(string f_series, string f_number, string su, string sp);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class get_ser_usersResponseGet_ser_usersResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_ser_users", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class get_ser_usersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string user_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string user_password;
        
        public get_ser_usersRequest()
        {
        }
        
        public get_ser_usersRequest(string user_name, string user_password)
        {
            this.user_name = user_name;
            this.user_password = user_password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_ser_usersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class get_ser_usersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public NtosService.get_ser_usersResponseGet_ser_usersResult get_ser_usersResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int user_id;
        
        public get_ser_usersResponse()
        {
        }
        
        public get_ser_usersResponse(NtosService.get_ser_usersResponseGet_ser_usersResult get_ser_usersResult, int user_id)
        {
            this.get_ser_usersResult = get_ser_usersResult;
            this.user_id = user_id;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class get_ser_users_notesResponseGet_ser_users_notesResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="chek", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class chekRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string su;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int user_id;
        
        public chekRequest()
        {
        }
        
        public chekRequest(string su, string sp, int user_id)
        {
            this.su = su;
            this.sp = sp;
            this.user_id = user_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="chekResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class chekResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool chekResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int user_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int sua;
        
        public chekResponse()
        {
        }
        
        public chekResponse(bool chekResult, int user_id, int sua)
        {
            this.chekResult = chekResult;
            this.user_id = user_id;
            this.sua = sua;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="save_invoice", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class save_invoiceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int user_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int invois_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.DateTime operation_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int seller_un_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int buyer_un_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string overhead_no;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public System.DateTime overhead_dt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int b_s_user_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string su;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string sp;
        
        public save_invoiceRequest()
        {
        }
        
        public save_invoiceRequest(int user_id, int invois_id, System.DateTime operation_date, int seller_un_id, int buyer_un_id, string overhead_no, System.DateTime overhead_dt, int b_s_user_id, string su, string sp)
        {
            this.user_id = user_id;
            this.invois_id = invois_id;
            this.operation_date = operation_date;
            this.seller_un_id = seller_un_id;
            this.buyer_un_id = buyer_un_id;
            this.overhead_no = overhead_no;
            this.overhead_dt = overhead_dt;
            this.b_s_user_id = b_s_user_id;
            this.su = su;
            this.sp = sp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="save_invoiceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class save_invoiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool save_invoiceResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int invois_id;
        
        public save_invoiceResponse()
        {
        }
        
        public save_invoiceResponse(bool save_invoiceResult, int invois_id)
        {
            this.save_invoiceResult = save_invoiceResult;
            this.invois_id = invois_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="save_invoice_a", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class save_invoice_aRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int user_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int invois_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.DateTime operation_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int seller_un_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int buyer_un_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string overhead_no;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public System.DateTime overhead_dt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int b_s_user_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string su;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string sp;
        
        public save_invoice_aRequest()
        {
        }
        
        public save_invoice_aRequest(int user_id, int invois_id, System.DateTime operation_date, int seller_un_id, int buyer_un_id, string overhead_no, System.DateTime overhead_dt, int b_s_user_id, string su, string sp)
        {
            this.user_id = user_id;
            this.invois_id = invois_id;
            this.operation_date = operation_date;
            this.seller_un_id = seller_un_id;
            this.buyer_un_id = buyer_un_id;
            this.overhead_no = overhead_no;
            this.overhead_dt = overhead_dt;
            this.b_s_user_id = b_s_user_id;
            this.su = su;
            this.sp = sp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="save_invoice_aResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class save_invoice_aResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool save_invoice_aResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int invois_id;
        
        public save_invoice_aResponse()
        {
        }
        
        public save_invoice_aResponse(bool save_invoice_aResult, int invois_id)
        {
            this.save_invoice_aResult = save_invoice_aResult;
            this.invois_id = invois_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_invoice", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class get_invoiceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int user_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int invois_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string su;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sp;
        
        public get_invoiceRequest()
        {
        }
        
        public get_invoiceRequest(int user_id, int invois_id, string su, string sp)
        {
            this.user_id = user_id;
            this.invois_id = invois_id;
            this.su = su;
            this.sp = sp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_invoiceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class get_invoiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool get_invoiceResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string f_series;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int f_number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.DateTime operation_dt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public System.DateTime reg_dt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int seller_un_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int buyer_un_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string overhead_no;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public System.DateTime overhead_dt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public int status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public string seq_num_s;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public string seq_num_b;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public int k_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public int r_un_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        public int k_type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=15)]
        public int b_s_user_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=16)]
        public int dec_status;
        
        public get_invoiceResponse()
        {
        }
        
        public get_invoiceResponse(
                    bool get_invoiceResult, 
                    string f_series, 
                    int f_number, 
                    System.DateTime operation_dt, 
                    System.DateTime reg_dt, 
                    int seller_un_id, 
                    int buyer_un_id, 
                    string overhead_no, 
                    System.DateTime overhead_dt, 
                    int status, 
                    string seq_num_s, 
                    string seq_num_b, 
                    int k_id, 
                    int r_un_id, 
                    int k_type, 
                    int b_s_user_id, 
                    int dec_status)
        {
            this.get_invoiceResult = get_invoiceResult;
            this.f_series = f_series;
            this.f_number = f_number;
            this.operation_dt = operation_dt;
            this.reg_dt = reg_dt;
            this.seller_un_id = seller_un_id;
            this.buyer_un_id = buyer_un_id;
            this.overhead_no = overhead_no;
            this.overhead_dt = overhead_dt;
            this.status = status;
            this.seq_num_s = seq_num_s;
            this.seq_num_b = seq_num_b;
            this.k_id = k_id;
            this.r_un_id = r_un_id;
            this.k_type = k_type;
            this.b_s_user_id = b_s_user_id;
            this.dec_status = dec_status;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class get_invoice_descResponseGet_invoice_descResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="save_invoice_desc", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class save_invoice_descRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int user_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string su;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int invois_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string goods;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string g_unit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public decimal g_number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public decimal full_amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public decimal drg_amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public decimal aqcizi_amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public int akciz_id;
        
        public save_invoice_descRequest()
        {
        }
        
        public save_invoice_descRequest(int user_id, int id, string su, string sp, int invois_id, string goods, string g_unit, decimal g_number, decimal full_amount, decimal drg_amount, decimal aqcizi_amount, int akciz_id)
        {
            this.user_id = user_id;
            this.id = id;
            this.su = su;
            this.sp = sp;
            this.invois_id = invois_id;
            this.goods = goods;
            this.g_unit = g_unit;
            this.g_number = g_number;
            this.full_amount = full_amount;
            this.drg_amount = drg_amount;
            this.aqcizi_amount = aqcizi_amount;
            this.akciz_id = akciz_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="save_invoice_descResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class save_invoice_descResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool save_invoice_descResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int id;
        
        public save_invoice_descResponse()
        {
        }
        
        public save_invoice_descResponse(bool save_invoice_descResult, int id)
        {
            this.save_invoice_descResult = save_invoice_descResult;
            this.id = id;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class get_ntos_invoices_inv_nosResponseGet_ntos_invoices_inv_nosResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_un_id_from_tin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class get_un_id_from_tinRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int user_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string tin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string su;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sp;
        
        public get_un_id_from_tinRequest()
        {
        }
        
        public get_un_id_from_tinRequest(int user_id, string tin, string su, string sp)
        {
            this.user_id = user_id;
            this.tin = tin;
            this.su = su;
            this.sp = sp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_un_id_from_tinResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class get_un_id_from_tinResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int get_un_id_from_tinResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string name;
        
        public get_un_id_from_tinResponse()
        {
        }
        
        public get_un_id_from_tinResponse(int get_un_id_from_tinResult, string name)
        {
            this.get_un_id_from_tinResult = get_un_id_from_tinResult;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_tin_from_un_id", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class get_tin_from_un_idRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int user_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int un_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string su;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sp;
        
        public get_tin_from_un_idRequest()
        {
        }
        
        public get_tin_from_un_idRequest(int user_id, int un_id, string su, string sp)
        {
            this.user_id = user_id;
            this.un_id = un_id;
            this.su = su;
            this.sp = sp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_tin_from_un_idResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class get_tin_from_un_idResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string get_tin_from_un_idResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string name;
        
        public get_tin_from_un_idResponse()
        {
        }
        
        public get_tin_from_un_idResponse(string get_tin_from_un_idResult, string name)
        {
            this.get_tin_from_un_idResult = get_tin_from_un_idResult;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="k_invoice", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class k_invoiceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int user_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int inv_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int k_type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string su;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string sp;
        
        public k_invoiceRequest()
        {
        }
        
        public k_invoiceRequest(int user_id, int inv_id, int k_type, string su, string sp)
        {
            this.user_id = user_id;
            this.inv_id = inv_id;
            this.k_type = k_type;
            this.su = su;
            this.sp = sp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="k_invoiceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class k_invoiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool k_invoiceResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int k_id;
        
        public k_invoiceResponse()
        {
        }
        
        public k_invoiceResponse(bool k_invoiceResult, int k_id)
        {
            this.k_invoiceResult = k_invoiceResult;
            this.k_id = k_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="g_invoice", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class g_invoiceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int user_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int inv_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string su;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sp;
        
        public g_invoiceRequest()
        {
        }
        
        public g_invoiceRequest(int user_id, int inv_id, string su, string sp)
        {
            this.user_id = user_id;
            this.inv_id = inv_id;
            this.su = su;
            this.sp = sp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="g_invoiceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class g_invoiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool g_invoiceResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int k_id;
        
        public g_invoiceResponse()
        {
        }
        
        public g_invoiceResponse(bool g_invoiceResult, int k_id)
        {
            this.g_invoiceResult = g_invoiceResult;
            this.k_id = k_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_makoreqtirebeli", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class get_makoreqtirebeliRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int user_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int inv_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string su;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sp;
        
        public get_makoreqtirebeliRequest()
        {
        }
        
        public get_makoreqtirebeliRequest(int user_id, int inv_id, string su, string sp)
        {
            this.user_id = user_id;
            this.inv_id = inv_id;
            this.su = su;
            this.sp = sp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_makoreqtirebeliResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class get_makoreqtirebeliResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool get_makoreqtirebeliResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int k_id;
        
        public get_makoreqtirebeliResponse()
        {
        }
        
        public get_makoreqtirebeliResponse(bool get_makoreqtirebeliResult, int k_id)
        {
            this.get_makoreqtirebeliResult = get_makoreqtirebeliResult;
            this.k_id = k_id;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class get_seller_invoicesResponseGet_seller_invoicesResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class get_buyer_invoicesResponseGet_buyer_invoicesResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class get_invoice_numbersResponseGet_invoice_numbersResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class get_invoice_tinsResponseGet_invoice_tinsResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class get_invoice_dResponseGet_invoice_dResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class get_seller_invoices_rResponseGet_seller_invoices_rResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class get_buyer_invoices_rResponseGet_buyer_invoices_rResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class print_invoicesResponsePrint_invoicesResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class get_akcizResponseGet_akcizResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class get_seq_numsResponseGet_seq_numsResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_invoice_request", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class get_invoice_requestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int inv_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int user_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string su;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sp;
        
        public get_invoice_requestRequest()
        {
        }
        
        public get_invoice_requestRequest(int inv_id, int user_id, string su, string sp)
        {
            this.inv_id = inv_id;
            this.user_id = user_id;
            this.su = su;
            this.sp = sp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_invoice_requestResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class get_invoice_requestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool get_invoice_requestResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int bayer_un_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int seller_un_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string overhead_no;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public System.DateTime dt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string notes;
        
        public get_invoice_requestResponse()
        {
        }
        
        public get_invoice_requestResponse(bool get_invoice_requestResult, int bayer_un_id, int seller_un_id, string overhead_no, System.DateTime dt, string notes)
        {
            this.get_invoice_requestResult = get_invoice_requestResult;
            this.bayer_un_id = bayer_un_id;
            this.seller_un_id = seller_un_id;
            this.overhead_no = overhead_no;
            this.dt = dt;
            this.notes = notes;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class get_requested_invoicesResponseGet_requested_invoicesResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class get_invoice_requestsResponseGet_invoice_requestsResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_seller_filter_count", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class get_seller_filter_countRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int un_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int user_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string su;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sp;
        
        public get_seller_filter_countRequest()
        {
        }
        
        public get_seller_filter_countRequest(int un_id, int user_id, string su, string sp)
        {
            this.un_id = un_id;
            this.user_id = user_id;
            this.su = su;
            this.sp = sp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_seller_filter_countResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class get_seller_filter_countResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool get_seller_filter_countResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int st_0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int st_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int st_4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int st_5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int st_6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int st_2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int st_3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public int st_7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public int st_8;
        
        public get_seller_filter_countResponse()
        {
        }
        
        public get_seller_filter_countResponse(bool get_seller_filter_countResult, int st_0, int st_1, int st_4, int st_5, int st_6, int st_2, int st_3, int st_7, int st_8)
        {
            this.get_seller_filter_countResult = get_seller_filter_countResult;
            this.st_0 = st_0;
            this.st_1 = st_1;
            this.st_4 = st_4;
            this.st_5 = st_5;
            this.st_6 = st_6;
            this.st_2 = st_2;
            this.st_3 = st_3;
            this.st_7 = st_7;
            this.st_8 = st_8;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_buyer_filter_count", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class get_buyer_filter_countRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int un_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int user_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string su;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sp;
        
        public get_buyer_filter_countRequest()
        {
        }
        
        public get_buyer_filter_countRequest(int un_id, int user_id, string su, string sp)
        {
            this.un_id = un_id;
            this.user_id = user_id;
            this.su = su;
            this.sp = sp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_buyer_filter_countResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class get_buyer_filter_countResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool get_buyer_filter_countResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int st_1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int st_5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int st_6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int st_2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int st_3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int st_7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int st_8;
        
        public get_buyer_filter_countResponse()
        {
        }
        
        public get_buyer_filter_countResponse(bool get_buyer_filter_countResult, int st_1, int st_5, int st_6, int st_2, int st_3, int st_7, int st_8)
        {
            this.get_buyer_filter_countResult = get_buyer_filter_countResult;
            this.st_1 = st_1;
            this.st_5 = st_5;
            this.st_6 = st_6;
            this.st_2 = st_2;
            this.st_3 = st_3;
            this.st_7 = st_7;
            this.st_8 = st_8;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class get_invoice_changesResponseGet_invoice_changesResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface NtosServiceSoapChannel : NtosService.NtosServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class NtosServiceSoapClient : System.ServiceModel.ClientBase<NtosService.NtosServiceSoap>, NtosService.NtosServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NtosServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(NtosServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), NtosServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NtosServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NtosServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NtosServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NtosServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NtosServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> what_is_my_ipAsync()
        {
            return base.Channel.what_is_my_ipAsync();
        }
        
        public System.Threading.Tasks.Task<bool> create_ser_userAsync(string user_name, string user_password, string ip, string notes, string su, string sp)
        {
            return base.Channel.create_ser_userAsync(user_name, user_password, ip, notes, su, sp);
        }
        
        public System.Threading.Tasks.Task<bool> update_ser_userAsync(string user_name, string user_password, string ip, string notes, string su, string sp)
        {
            return base.Channel.update_ser_userAsync(user_name, user_password, ip, notes, su, sp);
        }
        
        public System.Threading.Tasks.Task<NtosService.get_ser_usersResponse> get_ser_usersAsync(NtosService.get_ser_usersRequest request)
        {
            return base.Channel.get_ser_usersAsync(request);
        }
        
        public System.Threading.Tasks.Task<NtosService.get_ser_users_notesResponseGet_ser_users_notesResult> get_ser_users_notesAsync(string tin)
        {
            return base.Channel.get_ser_users_notesAsync(tin);
        }
        
        public System.Threading.Tasks.Task<NtosService.chekResponse> chekAsync(NtosService.chekRequest request)
        {
            return base.Channel.chekAsync(request);
        }
        
        public System.Threading.Tasks.Task<NtosService.save_invoiceResponse> save_invoiceAsync(NtosService.save_invoiceRequest request)
        {
            return base.Channel.save_invoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<NtosService.save_invoice_aResponse> save_invoice_aAsync(NtosService.save_invoice_aRequest request)
        {
            return base.Channel.save_invoice_aAsync(request);
        }
        
        public System.Threading.Tasks.Task<NtosService.get_invoiceResponse> get_invoiceAsync(NtosService.get_invoiceRequest request)
        {
            return base.Channel.get_invoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<NtosService.get_invoice_descResponseGet_invoice_descResult> get_invoice_descAsync(int user_id, int invois_id, string su, string sp)
        {
            return base.Channel.get_invoice_descAsync(user_id, invois_id, su, sp);
        }
        
        public System.Threading.Tasks.Task<NtosService.save_invoice_descResponse> save_invoice_descAsync(NtosService.save_invoice_descRequest request)
        {
            return base.Channel.save_invoice_descAsync(request);
        }
        
        public System.Threading.Tasks.Task<bool> delete_invoice_descAsync(int user_id, int id, int inv_id, string su, string sp)
        {
            return base.Channel.delete_invoice_descAsync(user_id, id, inv_id, su, sp);
        }
        
        public System.Threading.Tasks.Task<NtosService.get_ntos_invoices_inv_nosResponseGet_ntos_invoices_inv_nosResult> get_ntos_invoices_inv_nosAsync(int user_id, int invois_id, string su, string sp)
        {
            return base.Channel.get_ntos_invoices_inv_nosAsync(user_id, invois_id, su, sp);
        }
        
        public System.Threading.Tasks.Task<bool> save_ntos_invoices_inv_nosAsync(int invois_id, int user_id, string overhead_no, System.DateTime overhead_dt, string su, string sp)
        {
            return base.Channel.save_ntos_invoices_inv_nosAsync(invois_id, user_id, overhead_no, overhead_dt, su, sp);
        }
        
        public System.Threading.Tasks.Task<bool> delete_ntos_invoices_inv_nosAsync(int user_id, int id, int inv_id, string su, string sp)
        {
            return base.Channel.delete_ntos_invoices_inv_nosAsync(user_id, id, inv_id, su, sp);
        }
        
        public System.Threading.Tasks.Task<NtosService.get_un_id_from_tinResponse> get_un_id_from_tinAsync(NtosService.get_un_id_from_tinRequest request)
        {
            return base.Channel.get_un_id_from_tinAsync(request);
        }
        
        public System.Threading.Tasks.Task<NtosService.get_tin_from_un_idResponse> get_tin_from_un_idAsync(NtosService.get_tin_from_un_idRequest request)
        {
            return base.Channel.get_tin_from_un_idAsync(request);
        }
        
        public System.Threading.Tasks.Task<string> get_org_name_from_un_idAsync(int user_id, int un_id, string su, string sp)
        {
            return base.Channel.get_org_name_from_un_idAsync(user_id, un_id, su, sp);
        }
        
        public System.Threading.Tasks.Task<int> get_un_id_from_user_idAsync(int user_id, string su, string sp)
        {
            return base.Channel.get_un_id_from_user_idAsync(user_id, su, sp);
        }
        
        public System.Threading.Tasks.Task<bool> change_invoice_statusAsync(int user_id, int inv_id, int status, string su, string sp)
        {
            return base.Channel.change_invoice_statusAsync(user_id, inv_id, status, su, sp);
        }
        
        public System.Threading.Tasks.Task<bool> acsept_invoice_statusAsync(int user_id, int inv_id, int status, string su, string sp)
        {
            return base.Channel.acsept_invoice_statusAsync(user_id, inv_id, status, su, sp);
        }
        
        public System.Threading.Tasks.Task<bool> ref_invoice_statusAsync(int user_id, int inv_id, string ref_text, string su, string sp)
        {
            return base.Channel.ref_invoice_statusAsync(user_id, inv_id, ref_text, su, sp);
        }
        
        public System.Threading.Tasks.Task<NtosService.k_invoiceResponse> k_invoiceAsync(NtosService.k_invoiceRequest request)
        {
            return base.Channel.k_invoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<NtosService.g_invoiceResponse> g_invoiceAsync(NtosService.g_invoiceRequest request)
        {
            return base.Channel.g_invoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<NtosService.get_makoreqtirebeliResponse> get_makoreqtirebeliAsync(NtosService.get_makoreqtirebeliRequest request)
        {
            return base.Channel.get_makoreqtirebeliAsync(request);
        }
        
        public System.Threading.Tasks.Task<NtosService.get_seller_invoicesResponseGet_seller_invoicesResult> get_seller_invoicesAsync(int user_id, int un_id, System.DateTime s_dt, System.DateTime e_dt, System.DateTime op_s_dt, System.DateTime op_e_dt, string invoice_no, string sa_ident_no, string desc, string doc_mos_nom, string su, string sp)
        {
            return base.Channel.get_seller_invoicesAsync(user_id, un_id, s_dt, e_dt, op_s_dt, op_e_dt, invoice_no, sa_ident_no, desc, doc_mos_nom, su, sp);
        }
        
        public System.Threading.Tasks.Task<NtosService.get_buyer_invoicesResponseGet_buyer_invoicesResult> get_buyer_invoicesAsync(int user_id, int un_id, System.DateTime s_dt, System.DateTime e_dt, System.DateTime op_s_dt, System.DateTime op_e_dt, string invoice_no, string sa_ident_no, string desc, string doc_mos_nom, string su, string sp)
        {
            return base.Channel.get_buyer_invoicesAsync(user_id, un_id, s_dt, e_dt, op_s_dt, op_e_dt, invoice_no, sa_ident_no, desc, doc_mos_nom, su, sp);
        }
        
        public System.Threading.Tasks.Task<NtosService.get_invoice_numbersResponseGet_invoice_numbersResult> get_invoice_numbersAsync(int user_id, int un_id, string v_invoice_n, int v_count, string su, string sp)
        {
            return base.Channel.get_invoice_numbersAsync(user_id, un_id, v_invoice_n, v_count, su, sp);
        }
        
        public System.Threading.Tasks.Task<NtosService.get_invoice_tinsResponseGet_invoice_tinsResult> get_invoice_tinsAsync(int user_id, int un_id, string v_invoice_t, int v_count, string su, string sp)
        {
            return base.Channel.get_invoice_tinsAsync(user_id, un_id, v_invoice_t, v_count, su, sp);
        }
        
        public System.Threading.Tasks.Task<NtosService.get_invoice_dResponseGet_invoice_dResult> get_invoice_dAsync(int user_id, int un_id, string v_invoice_d, int v_count, string su, string sp)
        {
            return base.Channel.get_invoice_dAsync(user_id, un_id, v_invoice_d, v_count, su, sp);
        }
        
        public System.Threading.Tasks.Task<NtosService.get_seller_invoices_rResponseGet_seller_invoices_rResult> get_seller_invoices_rAsync(int user_id, int un_id, int status, string su, string sp)
        {
            return base.Channel.get_seller_invoices_rAsync(user_id, un_id, status, su, sp);
        }
        
        public System.Threading.Tasks.Task<NtosService.get_buyer_invoices_rResponseGet_buyer_invoices_rResult> get_buyer_invoices_rAsync(int user_id, int un_id, int status, string su, string sp)
        {
            return base.Channel.get_buyer_invoices_rAsync(user_id, un_id, status, su, sp);
        }
        
        public System.Threading.Tasks.Task<NtosService.print_invoicesResponsePrint_invoicesResult> print_invoicesAsync(int user_id, int inv_id, string su, string sp)
        {
            return base.Channel.print_invoicesAsync(user_id, inv_id, su, sp);
        }
        
        public System.Threading.Tasks.Task<NtosService.get_akcizResponseGet_akcizResult> get_akcizAsync(string s_text, int user_id, string su, string sp)
        {
            return base.Channel.get_akcizAsync(s_text, user_id, su, sp);
        }
        
        public System.Threading.Tasks.Task<NtosService.get_seq_numsResponseGet_seq_numsResult> get_seq_numsAsync(string sag_periodi, int user_id, string su, string sp)
        {
            return base.Channel.get_seq_numsAsync(sag_periodi, user_id, su, sp);
        }
        
        public System.Threading.Tasks.Task<bool> add_inv_to_declAsync(int user_id, int seq_num, int inv_id, string su, string sp)
        {
            return base.Channel.add_inv_to_declAsync(user_id, seq_num, inv_id, su, sp);
        }
        
        public System.Threading.Tasks.Task<bool> save_invoice_requestAsync(int inv_id, int user_id, int bayer_un_id, int seller_un_id, string overhead_no, System.DateTime dt, string notes, string su, string sp)
        {
            return base.Channel.save_invoice_requestAsync(inv_id, user_id, bayer_un_id, seller_un_id, overhead_no, dt, notes, su, sp);
        }
        
        public System.Threading.Tasks.Task<bool> del_invoice_requestAsync(int inv_id, int user_id, int bayer_un_id, string su, string sp)
        {
            return base.Channel.del_invoice_requestAsync(inv_id, user_id, bayer_un_id, su, sp);
        }
        
        public System.Threading.Tasks.Task<NtosService.get_invoice_requestResponse> get_invoice_requestAsync(NtosService.get_invoice_requestRequest request)
        {
            return base.Channel.get_invoice_requestAsync(request);
        }
        
        public System.Threading.Tasks.Task<bool> acsept_invoice_request_statusAsync(int id, int user_id, int seller_un_id, string su, string sp)
        {
            return base.Channel.acsept_invoice_request_statusAsync(id, user_id, seller_un_id, su, sp);
        }
        
        public System.Threading.Tasks.Task<NtosService.get_requested_invoicesResponseGet_requested_invoicesResult> get_requested_invoicesAsync(int user_id, int seller_un_id, string su, string sp)
        {
            return base.Channel.get_requested_invoicesAsync(user_id, seller_un_id, su, sp);
        }
        
        public System.Threading.Tasks.Task<NtosService.get_invoice_requestsResponseGet_invoice_requestsResult> get_invoice_requestsAsync(int bayer_un_id, int user_id, string su, string sp)
        {
            return base.Channel.get_invoice_requestsAsync(bayer_un_id, user_id, su, sp);
        }
        
        public System.Threading.Tasks.Task<NtosService.get_seller_filter_countResponse> get_seller_filter_countAsync(NtosService.get_seller_filter_countRequest request)
        {
            return base.Channel.get_seller_filter_countAsync(request);
        }
        
        public System.Threading.Tasks.Task<NtosService.get_buyer_filter_countResponse> get_buyer_filter_countAsync(NtosService.get_buyer_filter_countRequest request)
        {
            return base.Channel.get_buyer_filter_countAsync(request);
        }
        
        public System.Threading.Tasks.Task<NtosService.get_invoice_changesResponseGet_invoice_changesResult> get_invoice_changesAsync(int user_id, System.DateTime st_date, System.DateTime end_date, string su, string sp)
        {
            return base.Channel.get_invoice_changesAsync(user_id, st_date, end_date, su, sp);
        }
        
        public System.Threading.Tasks.Task<int> get_invoice_idAsync(string f_series, string f_number, string su, string sp)
        {
            return base.Channel.get_invoice_idAsync(f_series, f_number, su, sp);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NtosServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.NtosServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NtosServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.revenue.mof.ge/ntosservice/ntosservice.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.NtosServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.revenue.mof.ge/ntosservice/ntosservice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            NtosServiceSoap,
            
            NtosServiceSoap12,
        }
    }
}
